language: r

r:
  - oldrel
  - release
  - devel

sudo: false

cache: 
  - directories:
    - .check
    - .coverage
  - packages

install:
  - make .check/devtools .coverage/covr

script:
  - make check

after_success:
  - make coverage
