language: r

r:
  - oldrel
  - release
  - devel

sudo: false

cache: 
  - directories:
    - .check
    - .coverage
  - packages

r_packages:
  - devtools
  - roxygen2
  - covr

install: true

script:
  - make check

after_success:
  - make coverage
